### ISSUE TITLE
Unable to install turbo-server

### ISSUE THREAD

**Issue by manalipankaj** [geekskool/turbo-server#17]
Unable to install turbo-server to my project. Got this error:

>  CC(target) Release/obj.target/turbo_net/src/turbo_net.o
../src/turbo_net.c:2:22: fatal error: node_api.h: No such file or directory
compilation terminated.
turbo_net.target.mk:94: recipe for target 'Release/obj.target/turbo_net/src/turbo_net.o' failed
make: *** [Release/obj.target/turbo_net/src/turbo_net.o] Error 1
make: Leaving directory '/home/****/new-ui/node_modules/turbo-net/build'

**Comment by mukeshm** [comment]
When building turbo-net its not able to find node headers.
Can you do the follow the below steps and post the results
```
git clone https://github.com/mafintosh/turbo-net.git
cd turbo-net
node-gyp configure
node-gyp build
```

**Comment by manalipankaj** [comment]
Not able to 'node-gyp build', getting same error.

**Comment by mukeshm** [comment]
can you try
```
node-gyp list
node-gyp --silly build
```
Please post the output of the above commands on pastebin and provide the link.

**Comment by santoshrajan** [comment]
Which version of node are you using?

**Comment by manalipankaj** [comment]
v6.0

**Comment by santoshrajan** [comment]
Use the latest and try please.

**Comment by manalipankaj** [comment]
Worked with node v8.11.1. I think there is need of adding node version to readme. Not sure if it was because of node version only. Closing the issue. Thanks for resolving it.
